services:
  mysql-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: definitions
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql -ptest123 -e 'select 1'"]
      interval: 5s
      retries: 50
    networks:
      - app-network
 
  web-app:  
    build:
      context: $PWD
      dockerfile: web-app/Dockerfile.local
    depends_on:
      - mysql-db
    container_name: web-app
    ports:
      - "80:3000"
    volumes:
      - $PWD/web-app:/app/web-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
